export const SET_START_DATE = "SET_START_DATE";
export const SET_END_DATE = "SET_END_DATE";
export const SET_WEEK_NUMBER = "SET_WEEK_NUMBER";
export const SET_FROM_DATE = "SET_FROM_DATE";
export const SET_TO_DATE = "SET_TO_DATE";
export const WEEK_SET_SELECTED_DAYS = "WEEK_SET_SELECTED_DAYS";
