export const FETCH_TIMES_STARTED = "FETCH_TIMES_STARTED";
export const FETCH_TIMES_FAILED = "FETCH_TIMES_FAILED";
export const FETCH_TIMES_SUCESS = "FETCH_TIMES_SUCESS";

export const FETCH_WORKSPACE_STARTED = "FETCH_WORKSPACE_STARTED";
export const FETCH_WORKSPACE_FAILED = "FETCH_WORKSPACE_FAILED";
export const FETCH_WORKSPACE_SUCCESS = "FETCH_TIMES_SUCCESS";
