export const SET_CURRENT_WORKSPACE = "SET_CURRENT_WORKSPACE";
export const SET_WORKSPACES_FROM_TOGGL = "SET_WORKSPACES_FROM_TOGGL";

export const FETCH_WORKSPACE_STARTED = "FETCH_WORKSPACE_STARTED";
export const FETCH_WORKSPACE_FAILED = "FETCH_WORKSPACE_FAILED";
