export const SET_WORKSPACE_ID = "SET_WORKSPACE_ID";
export const SET_WORKSPACES_FROM_TOGGL = "SET_WORKSPACES_FROM_TOGGL";

export const FETCH_WORKSPACE_STARTED = "FETCH_WORKSPACE_STARTED";
export const FETCH_WORKSPACE_FAILED = "FETCH_WORKSPACE_FAILED";
export const FETCH_WORKSPACE_SUCCESS = "FETCH_TIMES_SUCCESS";
